### ISSUE TITLE
can not set location of switch/slider etc

### ISSUE THREAD

**Issue by sadatusa** [JaapDanielse/VirtualPanel#5]
Dear, Please add function to set size of panel, location of panel/switch/slider etc...

**Comment by JaapDanielse** [comment]
Hello Sadatusa,
It was a specific design choice not to implement setting locations an sizes of controls. 
I considered it, but it brings a lot issues and comes close to implementing HTML in the Arduino
and that is a burden I explicitly want to keep away from the Arduino developer.
An alternative is an application featuring a designer mode. I consider this for future development but as a separate project. If you want to have a go at this, please do! And keep me posted.
For this project I won't be implementing it, so I will close your issue. Sorry.
Regards, Jaap
