### ISSUE TITLE
Virtual panel will not find COM port 

### ISSUE THREAD

**Issue by Ian12345Ian** [JaapDanielse/VirtualPanel#6]
Hi 

I need help with Virtual-Panel old or new version is doing the same. When launch .exe the small display area flickers at high speed and will never find Arduino comport. I loaded numerous examples and green led never shows connected  Using win10 and win7. 
Can you make an exe to let me look for an available port. I have numerous applications on radio's PC and when try VirtualPanel all ports react some with PTT on commands, quite frightening for expensive radios, amps, sequencers, band switches, etc.     

Thank you for your help 
Ian
va3dif@gmail.com

**Comment by ardugnome** [comment]
Win11 sees the COM port and connects, but win10 does not, the virtual pane app flashes very rapidly and  states, not connected. Clicking the connect LED does nothing. Any chance to have a manual COM port selection and not stat scanning COM ports automatically? I believe for users with multiple COM ports or USB-COM port adapters, the program may hang on a device and not proceed forward. That might explain the rapid window flashing.

**Comment by JaapDanielse** [comment]
I have had no problems in win 10 or win 11. 
A user contacted me about a similar problem though where there were ports active  with data coming in when connected.
Solved this in Release 2.0.0 by a command line parameter allows to set a specific com port.

**Comment by Ian12345Ian** [comment]
Thank you very much Jaap. 
 
Great job !!!
 
Virtual Panel hamradio remote control application works great . No other
free application on the internet to make hamradio life easier.  
 
Bets regards
 
Ian
VA3DIF 

  _____

**Comment by JaapDanielse** [comment]
Glad to hear it! Thanks for the reply!

Op ma 16 sep 2024 om 15:37 schreef Ian12345Ian ***@***.***>:

**Comment by Ian12345Ian** [comment]
Hi Danielse,
 
Few years ago I developed a HF remote control  for my HF hamradio remote
control which works great !
 

 
Also did the remote for Moon bounce station : controls for azimuth and
elevation rotators with correction/calibration for positioning , antenna
polarity etc etc ....and works great! 
 

 
All the above VPs are working fine with win7 PCs using ArduinoPort.dll and
VirtualPanel.exe  version 1.0.0. (see attached). This VP version was built
for me only for me to solve "the serial port finding" problem and was never
released. 
  
Now I would like  to use VP on  a win10 PC but I encounter the same problem
of VP "automaticly" not finding the serial port. 
 
I even deleted the old VP versions and installed the latest version and
still doesn't work.  
 
Please let me know what should I do or even better if you have time to
develop a VP with port setup that will be great.
 
Thank you very very much for your help 
 
Traian (Ian)
VA3DIF

**Comment by JaapDanielse** [comment]
Hi Ian, 
In the latest version of VP the selection of a specific port I built in a special for you is implemented as well. 
You also can set a specific speed if that is required.
See https://github.com/JaapDanielse/VirtualPanel/wiki/Command-line
Hope this helps.

Jaap

**Comment by Ian12345Ian** [comment]
Hi Danielse
 
Will give it a try and will let you know if it works. 
 
Thank you very much 
 
Ian 
VA3DIF 

  _____

**Comment by Ian12345Ian** [comment]
it works !!!
 
Thank you very much 
 
Ian

  _____

**Comment by JaapDanielse** [comment]
You are welcome! :)

Op vr 1 mei 2026 om 22:08 schreef Ian12345Ian ***@***.***>:
