### ISSUE TITLE
VirtualPanel on Windows XP 

### ISSUE THREAD

**Issue by Liamtv7123** [JaapDanielse/VirtualPanel#7]
Hello, 

Is it possible to run this program on Windows XP? I am trying to run an Arduino and some old measurement equipment off an old computer. I am getting a "not valid Win 32 Application"

**Comment by JaapDanielse** [comment]
I guess windows XP is a bit too old for this application.
I am preparing to move to ,Net Core which is not supported by XP anyway. So I am not going to solve this. Sorry.
